#!/bin/sh

case "$1" in
	start)
		start-stop-daemon -S -n helloProcess -a /bin/hello
		;;
	stop)
		echo "Killing hello Process"
		start-stop-daemon -K -n helloProcess
		;;
	*)
		echo "Invaild argument"
		;;
esac
